services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    volumes:
      - ./:/var/www/html:delegated
      - ./storage:/var/www/html/storage
      - ./docker/php/entrypoint.sh:/usr/local/bin/entrypoint.sh:ro
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    env_file:
      - .env

  node:
    image: node:18-alpine
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm ci && npm run dev"
    depends_on:
      - app

  adminer:
    image: adminer:4.17.1
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    depends_on:
      - mysql

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      REDIS_HOSTS: local:redis:6379
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    command: sh -c "php artisan queue:work --sleep=3 --tries=3 --timeout=90"
    volumes:
      - ./:/var/www/html:delegated
    env_file:
      - .env
    depends_on:
      - app
      - redis

# ⚠️ Root-level volumes
volumes:
  node_modules: {}
